### ISSUE TITLE
Duplicate photos 

### ISSUE THREAD

**Issue by benchti** [jcfrog/tipibackup#11]
Merci @jcfrog pour l'outil 

Sur notre tipi après toutes ces années j'ai 13 000 photos dans 94 albums ;) . 

Je viens de me rendre compte que cela re-téléchargeait à chaque fois . 

Je vais RAZ les albums et refaire un par un consciencieusement mais c'était juste pour signaler si jamais c'est facile de faire le test si la photo est déjà là :  pas de téléchargement 

![image](https://github.com/jcfrog/tipibackup/assets/663816/2c2f48a0-d094-4663-956f-6b7e157a27fc)

**Comment by jcfrog** [comment]
oui c'est un peu compliqué parce que le test d'existence du fichier ne teste pas la présence physique sur la machine mais se sert de l'historique. L'idéal est de purger l'historique et supprimer tous les fichiers avant de relancer un backup complet...

**Comment by benchti** [comment]
Ok, c'est ce que je vais faire en sauvegardant chaque dossier ( Tout c'est trop long dans mon cas - sans quitter le navigateur et savoir si c'est terminé ) . Merci !
